### ISSUE TITLE
Counter does not need to be synchronized

### ISSUE THREAD

**Issue by vietj** [obsidian-toaster-quickstarts/rest_vertx#1]
https://github.com/obsidian-toaster/quick_rest_vertx/blob/master/src/main/java/org/jboss/obsidian/quickstart/RestApplication.java#L32

```
private final AtomicLong counter = new AtomicLong();
```

can be simply a long, please read about Vert.x concurrency model.

**Comment by cmoulliard** [comment]
Can we close this issue @vietj ?

**Comment by vietj** [comment]
no you are still using a `Long` value and not a `long` primitive type

**Comment by cescoffier** [comment]
Has been fixed.
